# Logistic Regression Example/Test

## Normalize

In [243]:
X1 = np.array([[1,3,5],[2,4,6]])
print("Number of rows:", X1.shape[0])
print("Number of columns:", X1.shape[1])

Number of rows: 2
Number of columns: 3


In [244]:
mean = np.mean(X1, axis = 0)
std = np.std(X1, axis = 0)
(X1-mean)/std

array([[-1., -1., -1.],
       [ 1.,  1.,  1.]])

## Add Bias Column

In [245]:
X1 = np.array([[1,3,5],[2,4,6]])

In [246]:
print("Number of rows:", X1.shape[0])
print("Number of columns:", X1.shape[1])

Number of rows: 2
Number of columns: 3


In [247]:
column_ones = np.ones(shape=(X1.shape[0], 1))
column_ones

array([[1.],
       [1.]])

In [248]:
X1 = np.concatenate((column_ones, X1), axis = 1)
X1

array([[1., 1., 3., 5.],
       [1., 2., 4., 6.]])

## Initialize Weights


In [249]:
weights1 = np.zeros((X1.shape[1], 1))
weights1

array([[0.],
       [0.],
       [0.],
       [0.]])

## Multiply Weights

In [250]:
np.dot(X1, weights1)

array([[0.],
       [0.]])

## Hypothesis

In [252]:
def sigmoid1(z):
        sig = 1/(1+np.exp(-z))
        return sig

In [253]:
h1 = sigmoid1(np.dot(X1, weights1))

## Gradient

In [254]:
y1 = np.array([[0], [1]])
y1.shape

(2, 1)

In [255]:
grad1 = (1 / m) * np.dot(X1.T, h1-y1)
weights1 -= 0.01 * grad1
weights1

array([[0.    ],
       [0.0025],
       [0.0025],
       [0.0025]])

## Number of labels = 1

In [258]:
y2 = np.array([[0], [1], [0], [1]])
np.sum(y2)

2

## Number of accurate labels

In [259]:
y1 = np.array([[1],[0],[1],[0]])
y2 = np.array([[0], [0], [1], [1]])
(y1 == y2).sum()

2