# Support Vector Machine from Scratch (using Numpy)

## Imports

In [3]:
import numpy as np
import pandas as pd # for data initialization
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer

## Initialize Data

In [ ]:
bc_data = load_breast_cancer()
df = pd.DataFrame(bc_data.data, columns=bc_data.feature_names)
df['target'] = bc_data.target

In [20]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns = ['target']), df['target'], random_state = 0, test_size = 0.2)

In [21]:
def normalize(X):
    mean = np.mean(X, axis = 0)
    std = np.std(X, axis = 0)
    return (X-mean) / std

In [ ]:
X_train = normalize(X_train)
X_test = normalize(X_test)

## Resources

* https://colab.research.google.com/drive/10amh3u9OhefFB0C-3lJo2H53x41I9GnJ?usp=sharing

* https://www.youtube.com/watch?v=WdXapAG6TYo

## SVM Model

In [ ]:
class SVM():
    def __init__(self, learning_rate=0.1, iterations=100, reg_term=1):
        self.learning_rate = learning_rate
        self.iterations = iterations
        self.reg_term = reg_term # regularization term
        self.costs = []

    def fit(self, X, y, stochastic=True):
        # Initialize Size
        self.m, self.n = X.shape

        # Initialize Weights, Bias, & Gradient
        self.w = np.zeros(self.n)
        self.b = 0

        self.X = X
        self.y = y

        if stochastic:
            for i in range(self.iterations):
                self.update_weights_sgd()
                self.costs.append(self.cost())
        else:
            for i in range(self.iterations):
                self.update_weights_bgd()
                self.costs.append(self.cost())

    def predict(self, X):
        p = np.dot(X, self.w) + self.b
        p = np.sign(p)
        p = np.where(p <= -1, 0, 1)
        return p

    def update_weights_sgd(self):
        # Stochastic Gradient Descent:
        for i, x_i in enumerate(self.X):

            p = self.y[i] * (np.dot(x_i, self.w) + self.b)

            if p >= 1:
                wg = 2 * self.reg_term * self.w
                bg = 0

            else:
                wg = 2 * self.reg_term * self.w - self.y[i] * x_i
                bg = self.y[i]

            self.w -= self.learning_rate * wg
            self.b -= self.learning_rate * bg

    def update_weights_bgd(self):

        # Batch Gradient Descent
        p = self.y * (np.dot(self.X, self.w) + self.b)

        wg_per_sample = np.where(p < 1, 2 * self.reg_term * self.w - np.dot(self.X, self.y), 2 * self.reg_term * self.w)
        bg_per_sample = np.where(p < 1, self.y, 0)

        wg = np.mean(wg_per_sample, axis = 0)
        bg = np.mean(bg_per_sample)

        self.w -= self.learning_rate * wg
        self.b -= self.learning_rate * bg

    def cost(self):
        p = np.dot(self.X, self.w) + self.b
        h_loss = np.sum(np.maximum(0, 1-self.y * p))
        cost = h_loss + 0.5 * np.dot(self.w, self.w)
        return cost

## Numpy examples

In [19]:
X1 = np.array([[1,3,2],[1,5,3]])
X1

array([[1, 3, 2],
       [1, 5, 3]])

In [5]:
p1 = np.sign(np.array([[1],[-3],[-4]]))
np.where(p1 <= -1, 0, 1)

array([[1],
       [0],
       [0]])

In [20]:
np.mean(X1, axis=0)

array([1. , 4. , 2.5])

In [14]:
for j, x in enumerate(X1):
    print(j)
    print(x)

0
[1 3 2]
1
[1 5 3]


In [15]:
X1[1]

array([1, 5, 3])

In [16]:
len(X1)

2

In [17]:
np.where(X1 >=3, 0, 1)

array([[1, 0, 1],
       [1, 0, 0]])

In [23]:
vector = np.array([1, 2, 3])
vector.shape

(3,)